### ISSUE TITLE
Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind

### ISSUE THREAD

**Issue by kuanyen** [Yuyz0112/vue-type-check#10]
```
$ npx vue-type-check --onlyTemplate --workspace .                                  (10-16 16:48)
Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind. /home/hentai/projects/waruimono/embeddedui/node_modules/@vue/cli-plugin-router/generator/template/src/App.vue.template
    at Object.assertEqual (/home/hentai/projects/waruimono/embeddedui/node_modules/typescript/lib/typescript.js:2193:17)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/home/hentai/projects/waruimono/embeddedui/node_modules/typescript/lib/typescript.js:135818:34)
    at tryReuseStructureFromOldProgram (/home/hentai/projects/waruimono/embeddedui/node_modules/typescript/lib/typescript.js:98326:28)
    at Object.createProgram (/home/hentai/projects/waruimono/embeddedui/node_modules/typescript/lib/typescript.js:97915:30)
    at synchronizeHostData (/home/hentai/projects/waruimono/embeddedui/node_modules/typescript/lib/typescript.js:135741:26)
    at Object.getSemanticDiagnostics (/home/hentai/projects/waruimono/embeddedui/node_modules/typescript/lib/typescript.js:135858:13)
    at VueInterpolationMode.doValidation (/home/hentai/projects/waruimono/embeddedui/node_modules/vue-language-server/dist/modes/template/interpolationMode.js:38:56)
    at /home/hentai/projects/waruimono/embeddedui/node_modules/vue-type-check/dist/index.js:77:47
    at Generator.next (<anonymous>)
    at fulfilled (/home/hentai/projects/waruimono/embeddedui/node_modules/vue-type-check/dist/index.js:5:58)
```

**Comment by rossjrw** [comment]
Same error here, slightly different log:

```
❯ vtc --workspace .
Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind.
    at getOrCreateSourceFileByPath (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:139355:34)
    at Object.getOrCreateSourceFile [as getSourceFile] (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:139313:24)
    at findSourceFile (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:101542:29)
    at /usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:101419:85
    at getSourceFileFromReferenceWorker (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:101386:34)
    at processSourceFile (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:101419:13)
    at processRootFile (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:101242:13)
    at /usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:100166:60
    at Object.forEach (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:317:30)
    at Object.createProgram (/usr/local/lib/node_modules/vue-type-check/node_modules/typescript/lib/typescript.js:100166:16)
```

**Comment by miyauchiakira** [comment]
Putting `--excludeDir node_modules` option seems solved this issue.

like
`vtc --workspace .`
↓
`vtc --workspace . --excludeDir node_modules`

( `excludeDir` was not on the [CLI options list](https://github.com/Yuyz0112/vue-type-check#cli), but in [Programmatical API](https://github.com/Yuyz0112/vue-type-check#programmatical-api) section. )
